apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "61.1.1"
    helm:
      values: |
        grafana:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.127-0-0-1.sslip.io
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.127-0-0-1.sslip.io
            annotations:
              cert-manager.io/cluster-issuer: "mkcert-issuer"
          
        prometheus:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - prometheus.127-0-0-1.sslip.io
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.127-0-0-1.sslip.io
            annotations:
              cert-manager.io/cluster-issuer: "mkcert-issuer"
              
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - alertmanager.127-0-0-1.sslip.io
            tls:
              - secretName: alertmanager-tls
                hosts:
                  - alertmanager.127-0-0-1.sslip.io
            annotations:
              cert-manager.io/cluster-issuer: "mkcert-issuer"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true